# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-23 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0006_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='resume',
            field=models.FileField(default=1, upload_to='students'),
            preserve_default=False,
        ),
    ]
