# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0009_auto_20171023_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='company_offer',
            name='interested_students',
            field=models.ManyToManyField(to='my_backend.applicant_details'),
        ),
    ]
