# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0010_auto_20171024_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicant_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='company_offer',
            name='interested_students',
        ),
        migrations.DeleteModel(
            name='applicant_details',
        ),
        migrations.AddField(
            model_name='company_offer',
            name='applicants',
            field=models.ManyToManyField(to='my_backend.applicant_detail'),
        ),
    ]
