# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0013_auto_20171024_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant_detail',
            name='status',
        ),
        migrations.RemoveField(
            model_name='company_offer',
            name='applicants',
        ),
        migrations.AddField(
            model_name='company_offer',
            name='interested_students',
            field=models.ManyToManyField(related_name='_company_offer_interested_students_+', to='my_backend.applicant_detail'),
        ),
        migrations.AddField(
            model_name='company_offer',
            name='shortlisted_students',
            field=models.ManyToManyField(related_name='_company_offer_shortlisted_students_+', to='my_backend.applicant_detail'),
        ),
    ]
