# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0017_auto_20171025_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='datetime',
            field=models.CharField(default=0.0012890431333663858, max_length=1000),
            preserve_default=False,
        ),
    ]
