# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0019_auto_20171025_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='offers',
            field=models.ManyToManyField(blank=True, to='my_backend.company_offer'),
        ),
    ]
