# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0020_auto_20171026_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='offers',
        ),
    ]
