# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-26 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_backend', '0021_remove_company_offers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_offer',
            name='interested_students',
        ),
        migrations.AddField(
            model_name='company_offer',
            name='interested_students',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='company_offer',
            name='shortlisted_students',
        ),
        migrations.AddField(
            model_name='company_offer',
            name='shortlisted_students',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
